# Generated by Django 5.2.5 on 2025-10-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='function',
            field=models.DateTimeField(),
        ),
    ]
