# Generated by Django 5.2.5 on 2025-10-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat',
            field=models.IntegerField(unique=True),
        ),
    ]
