# Generated by Django 5.2.5 on 2025-10-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='membership',
            field=models.IntegerField(choices=[(0, 'Ninguna'), (1, 'Básica'), (2, 'Premium'), (3, 'VIP')], default=0),
        ),
    ]
